<?php
global $cfg_Cs;
$cfg_Cs=array();
$cfg_Cs[2]=array(0,1,1,'5YWs5Y+45LuL57uN');
$cfg_Cs[6]=array(0,1,1,'5paw6Ze75Yqo5oCB');
$cfg_Cs[7]=array(6,1,1,'5YWs5Y+45paw6Ze7');
$cfg_Cs[8]=array(6,1,1,'6KGM5Lia5paw6Ze7');
$cfg_Cs[27]=array(2,1,1,'5Zui6Zif5LuL57uN');
$cfg_Cs[11]=array(0,1,1,'5Lqn5ZOB5bGV56S6');
$cfg_Cs[12]=array(11,1,1,'5pyN5Yqh6KGM5Lia');
$cfg_Cs[13]=array(11,1,1,'5pWZ6IKy6KGM5Lia');
$cfg_Cs[14]=array(11,1,1,'5oi/5Lqn6KGM5Lia');
$cfg_Cs[15]=array(11,1,1,'6IO95rqQ6KGM5Lia');
$cfg_Cs[25]=array(0,1,1,'6IGU57O75oiR5Lus');
$cfg_Cs[26]=array(25,1,1,'6IGU57O75oiR5Lus');
?>