<figure class="col-xs-12 col-sm-6 col-md-3 col-lg-3"><a href="[field:arcurl/]" title="[field:title/]" target="_blank" class="pic-link"><span class="hover-jia"></span><img src="[field:picname/]" class="img-circle ylw-img-responsive" alt="[field:title/]" ></a>
            <h3><a href='[field:arcurl/]'>[field:title/]</a><br>
              <small>[field:description function="cn_substr(@me,100)"/]...</small></h3>
          </figure>