<?php
$z[0]=Array("type"," <a href=\"[field:typelink/]\" target=\"_blank\">现在致电 0898-688989  OR  查看更多联系方式  &rarr;</a>",69,215);
$z[0][4]['typeid']="25";
$z[1]=Array("type"," <a href=\"[field:typelink/]\" rel=\"nofollow\">现在致电 0898-688989   OR  查看更多联系方式  &rarr;</a>",326,472);
$z[1][4]['typeid']="25";
$z[2]=Array("type"," <a href=\"[field:typelink/]\" class=\"bdsharebuttonbox\" rel=\"nofollow\"><img src=\"/skin/images/fenxiang.png\" width=\"18\" height=\"18\" alt=\"联系我们\" class=\"bds_more\" data-cmd=\"more\"></a>",2501,2721);
$z[2][4]['typeid']="25";
$z[3]=Array("type","\r\n              <li><a href=\"[field:typelink/]\" >[field:typename/]</a></li>\r\n              ",3026,3151);
$z[3][4]['typeid']="3";
$z[4]=Array("type","\r\n              <li><a href=\"[field:typelink/]\" >[field:typename/]</a></li>\r\n              ",3168,3293);
$z[4][4]['typeid']="5";
$z[5]=Array("type","\r\n              <li><a href=\"[field:typelink/]\" >[field:typename/]</a></li>\r\n              ",3310,3436);
$z[5][4]['typeid']="18";
$z[6]=Array("type","\r\n              <li><a href=\"[field:typelink/]\" >[field:typename/]</a></li>\r\n              ",3453,3579);
$z[6][4]['typeid']="19";
$z[7]=Array("type","\r\n              <li><a href=\"[field:typelink/]\" >[field:typename/]</a></li>\r\n              ",3596,3721);
$z[7][4]['typeid']="4";
$z[8]=Array("type","\r\n              <li><a href=\"[field:typelink/]\" >[field:typename/]</a></li>\r\n              ",3738,3864);
$z[8][4]['typeid']="26";
$z[9]=Array("channel","\r\n              <li><a href=\"[field:typeurl/]\" >[field:typename/]</a></li>\r\n              ",4018,4148);
$z[9][4]['type']="top";
$z[10]=Array("global","",4294,4320);
$z[10][4]['name']="cfg_webname";
$z[11]=Array("global","",4329,4355);
$z[11][4]['name']="cfg_webname";
$z[12]=Array("global","",4690,4716);
$z[12][4]['name']="cfg_powerby";
$z[13]=Array("flink","  [field:link /]  ",6131,6209);
$z[13][4]['titlelen']="20";
$z[13][4]['row']="20";
$z[13][4]['type']="text";
$z[14]=Array("type"," <a href=\"[field:typelink/]\" class=\"kefu-lx\" title=\"[field:typename/]\" target=\"_blank\">[field:typename/]</a>",7269,7412);
$z[14][4]['typeid']="25";

?>