<?php
$z[0]=Array("field","",220,239);
$z[0][4]['name']="title";
$z[1]=Array("global","",240,266);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",307,336);
$z[2][4]['name']="keywords";
$z[3]=Array("field","",376,434);
$z[3][4]['name']="description";
$z[3][4]['function']="html2text(@me)";
$z[4]=Array("include","",1062,1097);
$z[4][4]['filename']="head.htm";
$z[5]=Array("channel","\r\n        <li><a href='[field:typeurl/]'>[field:typename/]</a></li>\r\n        ",1625,1742);
$z[5][4]['type']="son";
$z[6]=Array("field","",1808,1837);
$z[6][4]['name']="position";
$z[7]=Array("channel"," <a href='[field:typeurl/]'>[field:typename/]</a> / \r\n        ",2711,2813);
$z[7][4]['type']="son";
$z[8]=Array("list","\r\n          <figure class=\"col-xs-12 col-sm-6 col-md-4 col-lg-4\"><a href=\"[field:arcurl/]\" title=\"[field:title/]\" target=\"_blank\" class=\"pic-link\"><span class=\"case-hover\"><span class=\"hover-link\"></span></span><img src=\"[field:picname/]\"  class=\"ylw-img-responsive3\" alt=\"[field:title/]\" /></a>\r\n            <h3><a href=\"[field:arcurl/]\" title=\"[field:title/]\" target=\"_blank\">[field:title/]</a><br />\r\n              <small>关注：[field:click/] / 目录：<a href='[field:typeurl/]'>[field:typename/]</a></small></h3>\r\n          </figure>\r\n          ",2957,3548);
$z[8][4]['pagesize']="6";
$z[9]=Array("pagelist","",3677,3748);
$z[9][4]['listitem']="info,index,end,pre,next,pageno";
$z[9][4]['listsize']="5";
$z[10]=Array("include","",3848,3885);
$z[10][4]['filename']="footer.htm";

?>