<?php
$z[0]=Array("field","",220,239);
$z[0][4]['name']="title";
$z[1]=Array("global","",240,266);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",307,336);
$z[2][4]['name']="keywords";
$z[3]=Array("field","",376,434);
$z[3][4]['name']="description";
$z[3][4]['function']="html2text(@me)";
$z[4]=Array("include","",1063,1098);
$z[4][4]['filename']="head.htm";
$z[5]=Array("channel","\r\n        <li><a href='[field:typeurl/]'>[field:typename/]</a></li>\r\n        ",1622,1739);
$z[5][4]['type']="son";
$z[6]=Array("field","",1805,1834);
$z[6][4]['name']="position";
$z[7]=Array("field","",1938,1959);
$z[7][4]['name']="content";
$z[8]=Array("type"," <a href=\"[field:typelink/]\" >立即前往 Now Go &rarr;</a>",2528,2623);
$z[8][4]['typeid']="17";
$z[9]=Array("type"," <a href=\"[field:typelink/]\" >立即前往 Now Go &rarr;</a>",3120,3215);
$z[9][4]['typeid']="11";
$z[10]=Array("include","",3298,3335);
$z[10][4]['filename']="footer.htm";

?>